styles
carouselCss
	^ '.carousel .nav {position:relative;padding:5px;border:1px solid #ccc;width:140px;height:100%}
	.carousel .inner {position:relative;margin:2px;overflow:hidden}
	.carousel .move {background:white;position:relative;top:0;left:0}
	.carousel .body {border:1px solid #ccc}
	.carousel .action {border:1px solid #ccc;background:#ffffe0;padding:2px}
	.carousel .nav a {text-decoration:none;color:black}
	.carousel td.right {text-align:right}
	.carousel .nav .active {background:#99ccff;border:1px dotted #ccc}' 