baselines-311-312
baseline312: spec
  "This groups all baseline"

  <version: '3.1.2-baseline'>
  self baseline311common: spec.
  self baseline311gemstone: spec.
  self baseline312pharo: spec.
  self baseline312slime: spec.
  self baseline311filesystem: spec.
  self baseline311adaptors: spec.
  self baseline311comet: spec.
  self baseline311javascript: spec.
  self baseline311jquery: spec.
  self baseline311jqueryui: spec.
  self baseline311rss: spec.
  self baseline311rest: spec.
  self baseline311scriptaculous: spec.
  self baseline311json: spec.
  self baseline311ob: spec.
  self baseline312gettext: spec.
  self baseline311welcome: spec