baselines-310
baseline310: spec
	<version: '3.1.0-baseline'>
	"This groups all baseline"
	self baseline310common: spec.
	self baseline310gemstone: spec.
	self baseline310pharo: spec.
	self baseline310filesystem: spec.
	self baseline310adaptors: spec.
	self baseline310comet: spec.
	self baseline310javascript: spec.
	self baseline310jquery: spec.
	self baseline310jqueryui: spec.
	self baseline310rss: spec.
	self baseline310scriptaculous: spec.
	self baseline310json: spec.
	self baseline310rest: spec.
	self baseline310ob: spec.
	self baseline310welcome: spec.