baselines-311-312
baseline311: spec
  "This groups all baseline"

  <version: '3.1.1-baseline'>
  self baseline311common: spec.
  self baseline311gemstone: spec.
  self baseline311pharo: spec.
  self baseline311filesystem: spec.
  self baseline311adaptors: spec.
  self baseline311comet: spec.
  self baseline311javascript: spec.
  self baseline311jquery: spec.
  self baseline311jqueryui: spec.
  self baseline311rss: spec.
  self baseline311rest: spec.
  self baseline311scriptaculous: spec.
  self baseline311json: spec.
  self baseline311ob: spec.
  self baseline311gettext: spec.
  self baseline311welcome: spec