private
addCountriesPerCurrencyCodeRemainingBecausePharo8LimitationOfLiteralsTo: dict

	^ dict  
			add:
			  'NZD'
			  -> #( 'Cook Islands' 'New Zealand' 'Niue' 'Pitcairn Islands'
				     'Tokelau' );
		  add: 'CRC' -> #( 'Costa Rica' );
		  add: 'CUP' -> #( 'Cuba' );
		  add: 'CZK' -> #( 'Czech Republic' );
		  add: 'DKK' -> #( 'Denmark' 'Faroe Islands' 'Greenland' );
		  add: 'DJF' -> #( 'Djibouti' );
		  add: 'DOP' -> #( 'Dominican Republic' );
		  add: 'ECS' -> #( 'Ecuador' );
		  add: 'EGP' -> #( 'Egypt' );
		  add: 'SVC' -> #( 'El Salvador' );
		  add: 'GBP'
			  ->
				  #( 'England' 'Northern Ireland' 'Scotland' 'South Georgia and the South Sandwich Islands'
				     'United Kingdom' 'Wales' );
		  add: 'ERN' -> #( 'Eritrea' );
		  add: 'SZL' -> #( 'Eswatini' );
		  add: 'ETB' -> #( 'Ethiopia' );
		  add: 'FKP' -> #( 'Falkland Islands' );
		  add: 'FJD' -> #( 'Fiji Islands' );
		  add:
			  'XPF'
			  -> #( 'French Polynesia' 'New Caledonia' 'Wallis and Futuna' );
		  add: 'GMD' -> #( 'Gambia' );
		  add: 'GEL' -> #( 'Georgia' );
		  add: 'GHS' -> #( 'Ghana' );
		  add: 'GIP' -> #( 'Gibraltar' );
		  add: 'QTQ' -> #( 'Guatemala' );
		  add: 'GNF' -> #( 'Guinea' );
		  add: 'CFA' -> #( 'Guinea-Bissau' );
		  add: 'GYD' -> #( 'Guyana' );
		  add: 'HTG' -> #( 'Haiti' );
		  add: 'HNL' -> #( 'Honduras' );
		  add: 'HKD' -> #( 'Hong Kong' );
		  add: 'HUF' -> #( 'Hungary' );
		  add: 'ISK' -> #( 'Iceland' );
		  add: 'INR' -> #( 'India' );
		  add: 'IDR' -> #( 'Indonesia' );
		  add: 'IRR' -> #( 'Iran' );
		  add: 'IQD' -> #( 'Iraq' );
		  add: 'ILS' -> #( 'Israel' );
		  add: 'JMD' -> #( 'Jamaica' );
		  add: 'JPY' -> #( 'Japan' );
		  add: 'JOD' -> #( 'Jordan' );
		  add: 'KZT' -> #( 'Kazakhstan' );
		  add: 'KES' -> #( 'Kenya' );
		  add: 'KWD' -> #( 'Kuwait' );
		  add: 'KGS' -> #( 'Kyrgyzstan' );
		  add: 'LAK' -> #( 'Laos' );
		  add: 'LBP' -> #( 'Lebanon' );
		  add: 'LSL' -> #( 'Lesotho' );
		  add: 'LRD' -> #( 'Liberia' );
		  add: 'LYD' -> #( 'Libya' );
		  add: 'CHF' -> #( 'Liechtenstein' 'Switzerland' );
		  add: 'MOP' -> #( 'Macau' );
		  add: 'MKD' -> #( 'North Macedonia' );
		  add: 'MGF' -> #( 'Madagascar' );
		  add: 'MWK' -> #( 'Malawi' );
		  add: 'MYR' -> #( 'Malaysia' );
		  add: 'MVR' -> #( 'Maldives' );
		  add: 'MRO' -> #( 'Mauritania' );
		  add: 'MUR' -> #( 'Mauritius' );
		  add: 'MXN' -> #( 'Mexico' );
		  add: 'MDL' -> #( 'Moldova' );
		  add: 'MNT' -> #( 'Mongolia' );
		  add: 'MAD' -> #( 'Morocco' 'Western Sahara' );
		  add: 'MZN' -> #( 'Mozambique' );
		  add: 'MMR' -> #( 'Myanmar' );
		  add: 'NAD' -> #( 'Namibia' );
		  add: 'NPR' -> #( 'Nepal' );
		  add: 'ANG' -> #( 'Netherlands Antilles' );
		  add: 'NIO' -> #( 'Nicaragua' );
		  add: 'NGN' -> #( 'Nigeria' );
		  add: 'KPW' -> #( 'North Korea' );
		  add: 'OMR' -> #( 'Oman' );
		  add: 'PKR' -> #( 'Pakistan' );
		  add: nil -> #( 'Palestine' );
		  add: 'PAB' -> #( 'Panama' );
		  add: 'PGK' -> #( 'Papua New Guinea' );
		  add: 'PYG' -> #( 'Paraguay' );
		  add: 'PEN' -> #( 'Peru' );
		  add: 'PHP' -> #( 'Philippines' );
		  add: 'PLN' -> #( 'Poland' );
		  add: 'QAR' -> #( 'Qatar' );
		  add: 'RON' -> #( 'Romania' );
		  add: 'RUB' -> #( 'Russia' );
		  add: 'RWF' -> #( 'Rwanda' );
		  add: 'SHP' -> #( 'Saint Helena' );
		  add: 'WST' -> #( 'Samoa' );
		  add: 'STD' -> #( 'Sao Tome and Principe' );
		  add: 'SAR' -> #( 'Saudi Arabia' );
		  add: 'RSD' -> #( 'Serbia' );
		  add: 'SCR' -> #( 'Seychelles' );
		  add: 'SLL' -> #( 'Sierra Leone' );
		  add: 'SGD' -> #( 'Singapore' );
		  add: 'SBD' -> #( 'Solomon Islands' );
		  add: 'SOS' -> #( 'Somalia' );
		  add: 'ZAR' -> #( 'South Africa' );
		  add: 'KRW' -> #( 'South Korea' );
		  add: 'SSP' -> #( 'South Sudan' );
		  add: 'LKR' -> #( 'Sri Lanka' );
		  add: 'SDG' -> #( 'Sudan' );
		  add: 'SRD' -> #( 'Suriname' );
		  add: 'SEK' -> #( 'Sweden' );
		  add: 'SYP' -> #( 'Syria' );
		  add: 'TJS' -> #( 'Tajikistan' );
		  add: 'TZS' -> #( 'Tanzania' );
		  add: 'THB' -> #( 'Thailand' );
		  add: 'CDF' -> #( 'The Democratic Republic of Congo' );
		  add: 'TOP' -> #( 'Tonga' );
		  add: 'TTD' -> #( 'Trinidad and Tobago' );
		  add: 'TND' -> #( 'Tunisia' );
		  add: 'TRY' -> #( 'Turkey' );
		  add: 'TMT' -> #( 'Turkmenistan' );
		  add: 'UGX' -> #( 'Uganda' );
		  add: 'UAH' -> #( 'Ukraine' );
		  add: 'AED' -> #( 'United Arab Emirates' );
		  add: 'UYU' -> #( 'Uruguay' );
		  add: 'UZS' -> #( 'Uzbekistan' );
		  add: 'VUV' -> #( 'Vanuatu' );
		  add: 'VEF' -> #( 'Venezuela' );
		  add: 'VND' -> #( 'Vietnam' );
		  add: 'YER' -> #( 'Yemen' );
		  add: 'ZMW' -> #( 'Zambia' );
		  add: 'ZWD' -> #( 'Zimbabwe' );
		  yourself