"
I am a stand in for an HTML root to render a web page without head or body.
"
Class {
	#name : 'WANilHtmlRoot',
	#superclass : 'WAObject',
	#category : 'Seaside-WebComponents-Core',
	#package : 'Seaside-WebComponents-Core'
}

{ #category : 'writing' }
WANilHtmlRoot >> closeOn: aDocument [
	"intentionally empty"
]

{ #category : 'writing' }
WANilHtmlRoot >> openOn: aDocument [
	"intentionally empty"
]
