resources
syntaxHighlightingCss	^ '
span.patternUnary  {
color:#000000;
font-weight:bold;
}

span.patternKeyword  {
color:#000000;
font-weight:bold;
}

span.patternArg {
color:#000088;
}

span.super  {
color:#008888;
}

span.instanceVar  {
color:#000088;
}

span.number  {
color:#880088;
}

span.receiver  {
color:#000088;
}

span.keyword  {
color:#000000;
}

span.string  {
color:#880088;
}

span.blockArg  {
color:#000088;
}

span.class  {
color:#000088;
}

span.self  {
color:#008888;
}

span.symbol  {
color:#880088;
}
'