baselines
baseline: spec

	<baseline>
	"This groups all baseline"
	self baselinecommon: spec.
	self baselinegemstone: spec.
	self baselinepharo: spec.
	self baselinefilesystem: spec.
	self baselineadaptors: spec.
	self baselinecomet: spec.
	self baselinejavascript: spec.
	self baselinejquery: spec.
	self baselinejqueryui: spec.
	self baselinerss: spec.
	self baselinerest: spec.
	self baselinescriptaculous: spec.
	self baselinejson: spec.
	self baselineob: spec.
	self baselinegettext: spec.
	self baselinewelcome: spec.