styles
titlePaneCss
	^ '.titlePane .title {background:#e0e0e0;border-bottom-color:black;border-bottom-style:dotted;border-bottom-width:1px}
	.titlePane {border:4px solid #ccc;width:450px;overflow:hidden}
	.titlePane .body {background:white;height:100%;width:100%;overflow:hidden}
	.titlePane .closed {height:0px;display:none}
	.titlePane a.title {cursor:pointer;
					outline: none;
					padding: 0.25em;
					display: block;
					text-decoration:none;
					color:black}
	.titlePane td.label {width:100%;white-space:nowrap}
	.titlePane .gfx {background-position: center center;
					width:16px;height:10px;
					background-image: url(arrowright.gif)}
	.titlePane .gfxopen {background-position: center center;
					width:16px;height:10px;
					background-image: url(arrowdown.gif)}
	'