ambiguous
schemes: aCollectionOfStrings
	"swagger object: The transfer protocol of the API. Values MUST be from the list: 'http', 'https', 'ws', 'wss'. If the schemes is not included, the default scheme to be used is the one used to access the Swagger definition itself.
	responses object: The transfer protocol for the operation. Values MUST be from the list: 'http', 'https', 'ws', 'wss'. The value overrides the Swagger Object schemes definition."
	self key: 'schemes' value: aCollectionOfStrings