tests - test data
sortedTripletsString

	^ '#: WAGettextExample>>renderContentOn:', String lf,
							'msgid "fontsize"', String lf,
							'msgstr ""', String lf, String cr,
							'#: WAGettextExample>>renderLocaleSelectionOn:', String lf,
							'msgid "Select a locale below"', String lf,
							'msgstr ""', String lf, String cr,
							'#: WAGettextExample>>renderLocaleSelectionOn:', String lf,
							'msgid "locale"', String lf,
							'msgstr ""', String lf, String cr.