tests - test data
translationLiteralsArray
	^ { 
	'Select a locale below'->(OrderedCollection newFrom: {
(WAGettextExample>>#renderLocaleSelectionOn:) asRingDefinition.
(WAGettextExample>>#renderLocaleSelectionOn:) asRingDefinition.
(WAGettextExample>>#renderLocaleSelectionOn:) asRingDefinition.
(WAGettextExample>>#renderLocaleSelectionOn:) asRingDefinition.
(WAGettextExample>>#renderLocaleSelectionOn:) asRingDefinition.
(WAGettextExample>>#renderLocaleSelectionOn:) asRingDefinition.
(WAGettextExample>>#renderLocaleSelectionOn:) asRingDefinition.
(WAGettextExample>>#renderLocaleSelectionOn:) asRingDefinition.
}).
'fontsize'->(OrderedCollection newFrom: {
(WAGettextExample>>#renderContentOn:) asRingDefinition.
(WAGettextExample>>#renderContentOn:) asRingDefinition.
(WAGettextExample>>#renderContentOn:) asRingDefinition.
(WAGettextExample>>#renderContentOn:) asRingDefinition.
}).
'locale'->(OrderedCollection newFrom: {
(WAGettextExample>>#renderLocaleSelectionOn:) asRingDefinition.
(WAGettextExample>>#renderLocaleSelectionOn:) asRingDefinition.
(WAGettextExample>>#renderLocaleSelectionOn:) asRingDefinition.
(WAGettextExample>>#renderLocaleSelectionOn:) asRingDefinition.
(WAGettextExample>>#renderLocaleSelectionOn:) asRingDefinition.
(WAGettextExample>>#renderLocaleSelectionOn:) asRingDefinition.
(WAGettextExample>>#renderLocaleSelectionOn:) asRingDefinition.
(WAGettextExample>>#renderLocaleSelectionOn:) asRingDefinition.
}) 
}.