tests - test data
translationLiteralsArrayAsCompiledMethod
	^ { 
	'Select a locale below'->(OrderedCollection newFrom: {
(WAGettextExample>>#renderLocaleSelectionOn:).
(WAGettextExample>>#renderLocaleSelectionOn:).
(WAGettextExample>>#renderLocaleSelectionOn:).
(WAGettextExample>>#renderLocaleSelectionOn:).
(WAGettextExample>>#renderLocaleSelectionOn:).
(WAGettextExample>>#renderLocaleSelectionOn:).
(WAGettextExample>>#renderLocaleSelectionOn:).
(WAGettextExample>>#renderLocaleSelectionOn:).
}).
'fontsize'->(OrderedCollection newFrom: {
(WAGettextExample>>#renderContentOn:).
(WAGettextExample>>#renderContentOn:).
(WAGettextExample>>#renderContentOn:).
(WAGettextExample>>#renderContentOn:).
}).
'locale'->(OrderedCollection newFrom: {
(WAGettextExample>>#renderLocaleSelectionOn:).
(WAGettextExample>>#renderLocaleSelectionOn:).
(WAGettextExample>>#renderLocaleSelectionOn:).
(WAGettextExample>>#renderLocaleSelectionOn:).
(WAGettextExample>>#renderLocaleSelectionOn:).
(WAGettextExample>>#renderLocaleSelectionOn:).
(WAGettextExample>>#renderLocaleSelectionOn:).
(WAGettextExample>>#renderLocaleSelectionOn:).
}) 
}.