ambiguous
description: aString
	"info object: A short description of the application. GFM syntax can be used for rich text representation.
	operation object: A verbose explanation of the operation behavior. GFM syntax can be used for rich text representation.
	response object: Required. A short description of the response. GFM syntax can be used for rich text representation."
	self key: 'description' value: aString