ambiguous
tags: aCollection
	"swagger object: A list of tags used by the specification with additional metadata. The order of the tags can be used to reflect on their order by the parsing tools. Not all tags that are used by the Operation Object must be declared. The tags that are not declared may be organized randomly or based on the tools' logic. Each tag name in the list MUST be unique.
	operation object: A list of tags for API documentation control. Tags can be used for logical grouping of operations by resources or any other qualifier."
	self key: 'tags' value: aCollection