styles
defaultUiCss
	^ '#theme { clear: both; float: right; margin: -40px 0 10px 0; }
#theme label { color: #fff; }
#theme select { outline: none; border: 1px solid #ddd; background-color: #fff; }
	
/* colors */
.blue { background-color: #68bfef; border: 2px solid #0090df; }
.red { background-color: #ef2929; border: 2px solid #cc0000; }
.green { background-color: #72d216; border: 2px solid #4e9a06; }
.brown { background-color: #e9b96e; border: 2px solid #c17d11; }

/* box */
.pack { position: relative; height: 110px; }
.box { float: left; width: 100px; height: 100px; margin-right: 1em; }'