hooks
style
	^ 'h1 {margin:0;padding:0;font-size:1.5em}
	div.bench {padding-left:4px;position:relative;line-height:36px;width:320px;border: 1px solid #ccc;overflow:hidden;float:left;margin-bottom:2px}
	div.result {margin:6px;color:#008aff;font-size:200%;font-weight:bold}
	span.iteration {margin-left:6px}
	div.rect {position:relative;border: 1px solid #ccc;;height:12px}
	.spi{float:left;padding-left:4px;padding-top:2px}
	'